### ISSUE TITLE
Worldgen crash Using Koresample 1.2.5 and Dendrology 1.3.0 [forge 10.13.2.1352]

### ISSUE THREAD

**Issue by ate0ate** [MinecraftModArchive/KoreSample#1]
After wandering around a new SSP world and generating new chunks, I got this crash out of the blue. I do indeed have Ancient Trees config set to generate trees in the overworld very rarely. So rarely I've yet to encounter one. With that being said, I am unsure if this is a weird one off crash or something that would happen every time an Ancient tree generates. I am using fastcraft, which is also mentioned in the crash report. I also use many mods, so the area attempting to generate does happen to be a Biomes O Plenty biome with an Applied Energistics 2 Meteor right in the vicinity, if either of those things even make any difference. Thank you for the great mod and I apologize if this issue turns out not to be Koresample's fault.

http://pastebin.com/zPBe8j67

**Comment by ScottKillen** [comment]
See MinecraftModArchive/Dendrology#30
